<?php

    include 'functions.php';

    echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Ghrello installation</title>
<link rel="stylesheet" type="text/css" href="css/view.css" media="all">
<script type="text/javascript" src="js/view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="css/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Ghrello installation</a></h1>
		<form id="form_install" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Ghrello installation</h2>
			<p>Please enter the settings below to configure your installation of Ghrello.</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Trello API Key </label>
		<div>
			<input id="trelloapikey" name="trelloapikey" class="element text large" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_1"><small>Enter your Trello API key which you can generate here: 
https://trello.com/1/appKey/generate</small></p> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Trello Board ID </label>
		<div>
			<input id="trelloboardid" name="trelloboardid" class="element text large" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_2"><small>Enter the trello board ID which is the last hex code in the URL (e.g. 506ac35636fa37ae13919ff8 in the link:
https://trello.com/board/dev-ghrello/506ac35636fa37ae13919ff8)</small></p> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Name of GitHub project </label>
		<div>
			<input id="ghproject" name="ghproject" class="element text large" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_3"><small>Enter the name of the GitHub project (e.g. ghrello from link: https://github.com/torstenfeld/ghrello/)</small></p> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="496896" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="css/bottom.png" alt="">
	</body>
</html>';

    require 'footer.php';


?>
