<?php

    require 'functions.php';
    
    echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
        <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Ghrello setup</title>
        <link rel="stylesheet" type="text/css" href="css/view.css" media="all">
        <script type="text/javascript" src="js/view.js"></script>

        </head>
        <body id="main_body" >
	
	<img id="top" src="css/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Ghrello setup</a></h1>
		<!-- <form id="form_install" class="appnitro"  method="post" action="setup.php"> -->
					<div class="form_description">
                                        <div id="header2">
			<h2>Ghrello setup</h2>
			<p>Please enter the settings below to configure your installation of Ghrello.</p>
		</div></div>	';
    
    
    
    
    echo '<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="css/bottom.png" alt="">
	</body>
</html>';



?>
